### ISSUE TITLE
Using native WebVR API without Google VR Services installed

### ISSUE THREAD

**Issue by arturitu** [googlevr/webvr-polyfill#199]
When I add the Origin trial token on a project, with public Chrome 56 it works OK on Daydream ready phones (like Pixel) it returns "Google, Inc. Daydream View” on VRDisplay and I can enter on Daydream mode. But when I tried the same project with a Nexus5 or a Samsung S6 or Note7 (non-daydream ready phones) VRDisplay returns "Cardboard VRDisplay (webvr-polyfill)” which seems to be correct, but if I have the meta of the WebVR token on the header, the camera doesn’t move with the accelerometer. But if I comment the meta, it works perfect. (On Chrome 55 worked fine)

I downloaded last version of the repo and I have upload to my server (which have https and Origin trial approved for this domain) two htmls, one similar to the basic example (without the meta) and another with the origin trial meta added.
[https://unboring.net/tmp/webvr-polyfill/](https://unboring.net/tmp/webvr-polyfill/)

With a Google Pixel (Android 7.1.1) + Chrome 56 >
- If you open [with Origin trial added](https://unboring.net/tmp/webvr-polyfill/basic/with.html) version.  **(OK)**
vrDisplay.displayName = "Google, Inc. Daydream View" > VR button go to Daydream mode.

- If you open [without Origin trial](https://unboring.net/tmp/webvr-polyfill/basic/) version. **(OK)**
vrDisplay.displayName = "Cardboard VRDisplay (webvr-polyfill)" > VR button go to Cardboard mode.

With a Nexus5/Samsung S6 (Android 6.0.1) + Chrome 56 >
- If you open [with Origin trial added](https://unboring.net/tmp/webvr-polyfill/basic/with.html) version. **BUG. Doesn't move the camera with the accelerometer.**
vrDisplay.displayName = "Cardboard VRDisplay (webvr-polyfill)" > VR button go to Cardboard mode.

- If you open [without Origin trial](https://unboring.net/tmp/webvr-polyfill/basic/) version. **(OK)**
vrDisplay.displayName = "Cardboard VRDisplay (webvr-polyfill)"> VR button go to Cardboard mode.

**Comment by klausw** [comment]
I can confirm this on my Nexus 5X, Chrome M56 enters the polyfill's display mode but there's no head tracking at all. @borismus , any ideas what's going on?

**Comment by klausw** [comment]
Ah, https://github.com/googlevr/webvr-polyfill/pull/197 looks like it should fix this.

**Comment by arturitu** [comment]
@klausw @brianchirls  I tested to add https://github.com/brianchirls/webvr-polyfill/tree/bounds-and-framedata as webvr-polyfill but still not working, os is necessary to change more things.

**Comment by brianchirls** [comment]
@arturitu Can you be more specific? Is there an error? anything in the console?

**Comment by brianchirls** [comment]
Actually on second thought, I think #197 might be a different bug. In that one, the screen is just blank because it throws an error and breaks the render loop.

**Comment by arturitu** [comment]
@brianchirls there isn't any error with your version. The only thing that keeps happening the same commented on my first comment of this issue. Yes, I think is a different bug.

**Comment by arturitu** [comment]
@HalfdanJ I just update the samples at [https://unboring.net/tmp/webvr-polyfill/](https://unboring.net/tmp/webvr-polyfill/) which is the same code of the last Master repo only adding in [with.html](https://unboring.net/tmp/webvr-polyfill/basic/with.html) the Origin Trial approved for my domain. And if is included, works well on a Google Pixel but stop to work on a Samsung S6 or a Nexus 5 (I suppose stop to work in any non Daydream ready phone). I can use Origin Trial in production because stop to work for this mobiles.

**Comment by jsantell** [comment]
Trying this out, and it may have changed since this was posted 2 months ago, but looks like the example with the origin trial isn't correctly linking to the webvr-polyfill, like the example without the origin trial.

![consolelog](https://cloud.githubusercontent.com/assets/641267/26514254/84e53fa6-4225-11e7-846a-ff278b1bd743.png)

**Comment by jsantell** [comment]
Trying this out on a [webvr.info sample](https://webvr.info/samples/03-vr-presentation.html?polyfill=1) which has the origin trial on, with the polyfill on, on Chrome 58, I get the same result where accelerometer doesn't   change any orientation.

This seems like a high priority.

**Comment by jsantell** [comment]
* Website: https://webvr.info/samples/03-vr-presentation.html?polyfill=1
* Nexus 6P (non-Daydream compatible) on Chrome M58 release and Chrome M61 Canary
* Android 6.0.1

`navigator.getVRDisplays()` never returns without Google VR Services installed and looks like that issue was found and fixed in M58, although I'm running into it in M58/M61, which the polyfill hangs on so none of the polyfill ever actually initializes.

Not sure if OP's issue is the same thing as above, or just https://github.com/googlevr/webvr-polyfill/issues/199#issuecomment-304398467

**Comment by jsantell** [comment]
I think installing Google VR Services would fix this issue, but not something we can count on users doing. Can anyone else confirm running into this and whether or not GVR Services are installed?

**Comment by jsantell** [comment]
Looks like this same issue: https://github.com/aframevr/aframe/issues/2444
